### ISSUE TITLE
晴男のWebAPIでの投稿でプロフ画像が反映されない

### ISSUE THREAD

**Issue by Khiroka** [april-knights-dev/weather_bot#34]
<img width="381" alt="スクリーンショット 2020-10-08 15 34 59" src="https://user-images.githubusercontent.com/29135359/95423319-d8ed7480-097b-11eb-86ba-ff09cec1882b.png">

**Comment by kiddykazz** [comment]
![image](https://user-images.githubusercontent.com/67847947/98116526-bd7a7880-1eeb-11eb-97bb-1c1b6f8bb8e6.png)
足がついたバージョンになったのでクローズ
